### ISSUE TITLE
Class cast upon weapon breaking if inventory includes a non-weapon

### ISSUE THREAD

**Issue by rayrobdod** [rayrobdod/FEMultiPlayer-V2#5]
Issue type: `problem`
#### Description:

Using b86dd177dbfe0d4329e50067d65c3ebea333130a with Unit.java line 569 (inside method public void `equip(Weapon w)`) changed from `if(stage != null){` to `if(stage != null && stage instanceof ClientOverworldStage){`:

Ewan holding, in order, a Eclipse (1/2), a Rise (3/4) and a dark tome (non-zero/non-zero). Ewan attacks Neimi using Eclipse. The attack animation plays, unlike Eli/95. Upon selecting End Turn, the server crashes.

Because apparently the 0/2 use eclipse hadn't been removed from the inventory in at least one place.
#### Examples:

```
[info] [RCVE]2 ENDTURN::
[info] [SEND]2 ENDTURN::
[info] [RCVE]2 COMMANDMESSAGE::[]
[info] [RCVE]1 COMMANDMESSAGE::[]
[info] [SEND]2 COMMANDMESSAGE::[]
[info] [SEND]1 COMMANDMESSAGE::[]
[info] [RCVE]1 COMMANDMESSAGE::Ewan move (0, 0):[EQUIP, Ewan, 0, EQUIP, Ewan, 0, EQUIP, Ewan, 0, EQUIP, Ewan, 0, EQUIP, Ewan, 0, EQUIP, Ewan, 0, EQUIP, Ewan, 0, EQUIP, Ewan, 0, EQUIP, Ewan, 0, ATTACK, Neimi]
[info] [BATL]0 BATTLESTART::
[info] [BATL]0 HP::Ewan HP30 Neimi HP27
[info] [BATL]0 ATTACKRECORD::Attack Miss: Ewan, Neimi, 0, 0 (drain)
[info] [BATL]0 HP::Ewan HP30 Neimi HP27
[info] [BATL]0 BATTLEEND::
[info] [SEND]1 COMMANDMESSAGE::Ewan move (0, 0):[EQUIP, Ewan, 0, EQUIP, Ewan, 0, EQUIP, Ewan, 0, EQUIP, Ewan, 0, EQUIP, Ewan, 0, EQUIP, Ewan, 0, EQUIP, Ewan, 0, EQUIP, Ewan, 0, EQUIP, Ewan, 0, ATTACK, Neimi]
[info] [RCVE]1 ENDTURN::
[info] [SEND]1 ENDTURN::
[info] [RCVE]2 COMMANDMESSAGE::[EQUIP, Ewan, 1]
[info] [RCVE]1 COMMANDMESSAGE::[EQUIP, Ewan, 1]
```

```
java.lang.ClassCastException: net.fe.unit.RiseTome cannot be cast to net.fe.unit.Weapon
    at net.fe.unit.Unit.equip(Unit.java:586)
    at net.fe.overworldStage.OverworldStage.processCommands(OverworldStage.java:378)
    at net.fe.overworldStage.OverworldStage.beginStep(OverworldStage.java:263)
    at net.fe.network.FEServer.loop(FEServer.java:347)
    at net.fe.network.FEServer$4$2.run(FEServer.java:263)
```

[logs.zip](https://github.com/rayrobdod/FEMultiPlayer-V2/files/276216/logs.zip)

**Comment by rayrobdod** [comment]
Solved sometime before 703ee89ca6ef141c40202eb4bf1b1b82e3c33a27
